name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        qt:
          - version: 5
            packages: qtbase5-dev qtbase5-dev-tools
          - version: 6
            packages: qt6-tools-dev qt6-base-dev libglx-dev libgl1-mesa-dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install ${{matrix.qt.packages}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCALFENSTER_QTVERSION=${{matrix.qt.version}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
