name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        bt:
          - name: "Qt5"
            qt_version: 5
            packages: qtbase5-dev
          - name: "Qt6 - Wayland"
            qt_version: 6
            packages: qt6-base-dev libglx-dev libgl1-mesa-dev liblayershellqtinterface-dev
          - name: "Qt6 - only X11"
            qt_version: 6
            packages: qt6-base-dev libglx-dev libgl1-mesa-dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install eatmydata ${{matrix.bt.name}}
      shell: bash
      run: |
        type eatmydata || sudo sh -c 'apt-get install -y eatmydata || apt-get update && apt-get install -y eatmydata'

    - name: Install dependencies ${{matrix.bt.name}}
      run: |
          sudo eatmydata apt install ${{matrix.bt.packages}}

    - name: Configure CMake ${{matrix.bt.name}}
      run: cmake -B ${{github.workspace}}/build -DCALFENSTER_QTVERSION=${{matrix.bt.qt_version}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build ${{matrix.bt.name}}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
